api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: ""  # overridden by TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL in compose.yaml
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
